/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.util.ArrayList;
import clases.Datos;
import clases.Administrador;
import clases.Persona;
import clases.Computador;
import clases.Vendedor;
import clases.Tecnico;
import clases.Accesorio;
import clases.Empleado;
import clases.Parte;
import javax.swing.JOptionPane;

/**
 *
 * @author Jerson Andino
 */
public class GUIHome extends javax.swing.JFrame {

    Datos misDatos;
    Administrador admin;
    ArrayList<Empleado> personas;
    ArrayList<Computador> equipos;

    
    /**
     * Creates new form NewJFrame
     */
    public GUIHome() {
        initComponents();
        
        
            admin = new Administrador("1234", "Jerson", "Andino", "1004998678");
            personas = new ArrayList<>();
            personas.add(new Vendedor(0.1, 0, "Juan", "Perez", "1004897564"));
            personas.add(new Vendedor(0.1, 0, "Pedrin", "Perez", "12"));
            personas.add(new Tecnico(0.1, 0, "Felipe", "Contr", "22222"));
            equipos = new ArrayList<>();
            equipos.add(new Accesorio("3000", 25, "BLABLA"));
            equipos.add(new Parte("2000", 35, "jhjh"));
            misDatos = new Datos(admin, personas, equipos);
      
            
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        pnlTipo = new javax.swing.JPanel();
        rbtAdministrador = new javax.swing.JRadioButton();
        rbtMantenimiento = new javax.swing.JRadioButton();
        rbtVenta = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        lblContrasena = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        psfContraseña = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Tipo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btgTipo.add(rbtAdministrador);
        rbtAdministrador.setText("Administrador");

        btgTipo.add(rbtMantenimiento);
        rbtMantenimiento.setText("Mantenimiento");

        btgTipo.add(rbtVenta);
        rbtVenta.setText("Venta");

        javax.swing.GroupLayout pnlTipoLayout = new javax.swing.GroupLayout(pnlTipo);
        pnlTipo.setLayout(pnlTipoLayout);
        pnlTipoLayout.setHorizontalGroup(
            pnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtAdministrador)
                .addGap(66, 66, 66)
                .addComponent(rbtMantenimiento)
                .addGap(75, 75, 75)
                .addComponent(rbtVenta)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlTipoLayout.setVerticalGroup(
            pnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAdministrador)
                    .addComponent(rbtMantenimiento)
                    .addComponent(rbtVenta)))
        );

        btnGuardar.setText("Ingresar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblContrasena.setText("Contraseña:");

        lblCedula.setText("Cedula:");

        psfContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psfContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCedula)
                .addGap(18, 18, 18)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasena)
                .addGap(18, 18, 18)
                .addComponent(psfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(psfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            int codigo;
            String cedula = txtCedula.getText();
            String contraseña = new String(psfContraseña.getPassword());
            

            if (rbtAdministrador.isSelected()) {
                if(misDatos.getAdmin().getCedula().equals(cedula) && misDatos.getAdmin().getCodigo().equals(contraseña)){
                    GUIAdministrador administrador = new GUIAdministrador();
                    this.setVisible(false);
                    administrador.setVisible(true);
                } 
                else
                    JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña invalidos");
                    
            }
            if (rbtMantenimiento.isSelected()) {
                boolean valido = false;
                int cont = 0;
                for(int i = 0; i < misDatos.getPersonas().size(); i++){
                    if(misDatos.getPersonas().get(i).getCedula().equals(cedula)){
                        valido = true;
                        cont = i;
                    }                      
                }
                if(valido == true && ((Tecnico)misDatos.getPersonas().get(cont)).getCodigo().equals(contraseña)){
                    
                    GUIMantenimiento mantenimiento = new GUIMantenimiento();
                    this.setVisible(false);
                    mantenimiento.setVisible(true);
                } 
                else
                    JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña invalidos");
                
            }
            if (rbtVenta.isSelected()) {
                boolean valido = false;
                int cont = 0;
                for(int i = 0; i < misDatos.getPersonas().size(); i++){
                    if(misDatos.getPersonas().get(i).getCedula().equals(cedula)){
                        valido = true;
                        cont = i;
                    }                      
                }
                if(valido == true && ((Vendedor)misDatos.getPersonas().get(cont)).getCodigo().equals(contraseña)){
                    GUIVenta ventas = new GUIVenta();
                    this.setVisible(false);
                    ventas.setVisible(true);
                } 
                else
                    JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña invalidos");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void psfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psfContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psfContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JPanel pnlTipo;
    private javax.swing.JPasswordField psfContraseña;
    private javax.swing.JRadioButton rbtAdministrador;
    private javax.swing.JRadioButton rbtMantenimiento;
    private javax.swing.JRadioButton rbtVenta;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
