/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import clases.Datos;
import clases.Administrador;
import clases.Persona;
import clases.Computador;
import clases.Vendedor;
import clases.Tecnico;
import clases.Accesorio;
import clases.DetalleVenta;
import clases.Parte;
import clases.Venta;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jerson Andino
 */
public class GUIVenta extends javax.swing.JFrame {
DefaultTableModel modeloTblProd, modeloTblDetalle;
Datos misDatos;
DefaultComboBoxModel modeloCombo;

    /**
     * Creates new form GUIVenta
     */
    public GUIVenta() {
        initComponents();
        GUIHome ventana = new GUIHome();
        this.misDatos = ventana.misDatos;
        modeloTblProd = new DefaultTableModel();
        modeloTblDetalle = new DefaultTableModel();
        modeloTblProd.addColumn("Codigo");
        modeloTblProd.addColumn("Nombre");
        modeloTblProd.addColumn("Precio");
        modeloTblProd.addColumn("Stock");
        tblProductos.setModel(modeloTblProd);
        modeloTblDetalle.addColumn("Codigo");
        modeloTblDetalle.addColumn("Nombre");
        modeloTblDetalle.addColumn("Precio");
        modeloTblDetalle.addColumn("Cantidad");
        modeloTblDetalle.addColumn("Precio total");
        tblDetalle.setModel(modeloTblDetalle);
        modeloCombo =  new DefaultComboBoxModel();
        for(int i= 0; i < misDatos.getPersonas().size(); i++){
            if(misDatos.getPersonas().get(i) instanceof Vendedor)
                modeloCombo.addElement(misDatos.getPersonas().get(i).getCedula());
        }
        cmbVendedor.setModel(modeloCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgEquipo = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        lblVendedor = new javax.swing.JLabel();
        cmbVendedor = new javax.swing.JComboBox<>();
        btnVender = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbnAccesorio = new javax.swing.JRadioButton();
        lblTipoProducto = new javax.swing.JLabel();
        rbnParte = new javax.swing.JRadioButton();
        rbnComputador = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblVendedor.setText("Vendedor:");

        cmbVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVender.setText("Vender");
        btnVender.setToolTipText("");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        btgEquipo.add(rbnAccesorio);
        rbnAccesorio.setText("Accesorios");
        rbnAccesorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAccesorioActionPerformed(evt);
            }
        });

        lblTipoProducto.setText("Producto:");

        btgEquipo.add(rbnParte);
        rbnParte.setText("Partes");
        rbnParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnParteActionPerformed(evt);
            }
        });

        btgEquipo.add(rbnComputador);
        rbnComputador.setText("Computador");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        lblNombre.setText("Nombre:");

        txtNombre.setEnabled(false);

        lblCodigo.setText("Codigo:");

        txtCodigo.setEnabled(false);

        lblPrecio.setText("Precio:");

        txtPrecio.setEnabled(false);

        lblCantidad.setText("Cantidad:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSeleccionar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(btnAgregar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTipoProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbnAccesorio)
                            .addGap(55, 55, 55)
                            .addComponent(rbnParte)
                            .addGap(70, 70, 70)
                            .addComponent(rbnComputador))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoProducto)
                    .addComponent(rbnAccesorio)
                    .addComponent(rbnParte)
                    .addComponent(rbnComputador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSeleccionar)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnAgregar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalle);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnModificar)
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnHome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(btnVender)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendedor)
                    .addComponent(cmbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVender)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        try{
            
            int index = tblProductos.getSelectedRow();
            txtCodigo.setText(modeloTblProd.getValueAt(index, 0).toString());
            txtNombre.setText(modeloTblProd.getValueAt(index, 1).toString());
            txtPrecio.setText(modeloTblProd.getValueAt(index, 2).toString());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try{
            modeloTblDetalle.addRow(new Object[]{(txtCodigo.getText()), txtNombre.getText(), Double.parseDouble(txtPrecio.getText()), Double.parseDouble(txtCantidad.getText()), Double.parseDouble(txtCantidad.getText()) * Double.parseDouble(txtPrecio.getText()) });
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void rbnAccesorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAccesorioActionPerformed
        // TODO add your handling code here:
        try{
            modeloTblProd.setRowCount(0);
            for(int i = 0; i< misDatos.getEquipos().size(); i++){
                if(misDatos.getEquipos().get(i) instanceof Accesorio){
                    String nombre = misDatos.getEquipos().get(i).getNombre();
                    String modelo = misDatos.getEquipos().get(i).getModelo();
                    double precio = misDatos.getEquipos().get(i).getPrecio();
                    modeloTblProd.addRow(new Object[]{"", nombre, precio, modelo});                        
                }                    
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_rbnAccesorioActionPerformed

    private void rbnParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnParteActionPerformed
        // TODO add your handling code here:
        try{
            modeloTblProd.setRowCount(0);
            for(int i = 0; i< misDatos.getEquipos().size(); i++){
                if(misDatos.getEquipos().get(i) instanceof Parte){
                    String nombre = misDatos.getEquipos().get(i).getNombre();
                    String modelo = misDatos.getEquipos().get(i).getModelo();
                    double precio = misDatos.getEquipos().get(i).getPrecio();
                    modeloTblProd.addRow(new Object[]{"", nombre, precio, modelo});                        
                }                    
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_rbnParteActionPerformed
    
    private void eliminarFila(){
        try{
            ArrayList<DetalleVenta> temp = new ArrayList<>();
            for(int i = 0; i<modeloTblDetalle.getRowCount(); i++){
                String modelo = modeloTblDetalle.getValueAt(i, 0).toString();
                String nombre = modeloTblDetalle.getValueAt(i, 1).toString();
                double precio = Double.parseDouble(modeloTblDetalle.getValueAt(i, 2).toString());
                Computador aux = new Computador(modelo, precio, nombre);
                temp.add(new DetalleVenta(aux, Double.parseDouble(modeloTblDetalle.getValueAt(i, 3).toString())));
            }
            int num = tblDetalle.getSelectedRow();
            temp.remove(num);
            modeloTblDetalle.setRowCount(0);
            for (int i= 0; i < temp.size(); i++){
                modeloTblDetalle.addRow(new Object[]{"", temp.get(i).getDetalle().getNombre(), temp.get(i).getDetalle().getPrecio(), temp.get(i).getCantidad(), temp.get(i).getPrecioTotal()});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try{
            /*ArrayList<DetalleVenta> temp = new ArrayList<>();
            for(int i = 0; i<modeloTblDetalle.getRowCount(); i++){
                String modelo = modeloTblDetalle.getValueAt(i, 0).toString();
                String nombre = modeloTblDetalle.getValueAt(i, 1).toString();
                double precio = Double.parseDouble(modeloTblDetalle.getValueAt(i, 2).toString());
                Computador aux = new Computador(modelo, precio, nombre);
                temp.add(new DetalleVenta(aux, Double.parseDouble(modeloTblDetalle.getValueAt(i, 3).toString())));
            }
            int num = tblDetalle.getSelectedRow();
            temp.remove(num);
            modeloTblDetalle.setRowCount(0);
            for (int i= 0; i < temp.size(); i++){
                modeloTblDetalle.addRow(new Object[]{"", temp.get(i).getDetalle().getNombre(), temp.get(i).getDetalle().getPrecio(), temp.get(i).getCantidad(), temp.get(i).getPrecioTotal()});
            }
            */
            eliminarFila();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            int num = tblDetalle.getSelectedRow();
            txtCodigo.setText(modeloTblDetalle.getValueAt(num, 0).toString());
            txtNombre.setText(modeloTblDetalle.getValueAt(num, 1).toString());
            txtPrecio.setText(modeloTblDetalle.getValueAt(num, 2).toString());
            
            eliminarFila();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        try{
            String cedula = (String)cmbVendedor.getSelectedItem();
            int cont=0;
            for(int i=0; i < misDatos.getPersonas().size(); i++){
                if(cedula.equals(misDatos.getPersonas().get(i).getCedula()))
                    cont = i;
                else
                    cont = cont;
            }
            ArrayList<DetalleVenta> temp = new ArrayList<>();
            for(int i = 0; i<modeloTblDetalle.getRowCount(); i++){
                String modelo = modeloTblDetalle.getValueAt(i, 0).toString();
                String nombre = modeloTblDetalle.getValueAt(i, 1).toString();
                double precio = Double.parseDouble(modeloTblDetalle.getValueAt(i, 2).toString());
                Computador aux = new Computador(modelo, precio, nombre);
                temp.add(new DetalleVenta(aux, Double.parseDouble(modeloTblDetalle.getValueAt(i, 3).toString())));
            }
            misDatos.getVentas().add(new Venta((misDatos.getVentas().size()+1), (Vendedor)misDatos.getPersonas().get(cont), temp));
            JOptionPane.showMessageDialog(rootPane, misDatos.getVentas().size());
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        GUIHome ventana = new GUIHome();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgEquipo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cmbVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipoProducto;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JRadioButton rbnAccesorio;
    private javax.swing.JRadioButton rbnComputador;
    private javax.swing.JRadioButton rbnParte;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
